# Generated by Django 5.1.3 on 2024-12-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paleta',
            name='imagen',
            field=models.ImageField(null=True, upload_to='paletas'),
        ),
    ]
